/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinic.system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Owner
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    
     int xmouse , ymouse;  // mouse coordinates
     String []value = new String[30];
     int i = 0;
     // define table columns names 
     final String [] column_names = new String [] {
                "Patient_name", "Pateint_age", "Address", "Phone_Number", "Patient's job", "Temperature", "Money_paid ", "Remaining money"};
    DefaultTableModel tableModel = new DefaultTableModel(column_names, 0);
    final String exported_path = "C:\\Users\\Owner\\Desktop\\exported.txt";
     
    public HomeFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.getTableHeader().setFont(new Font("Lucida Sans",Font.BOLD, 13));
        jTable1.getTableHeader().setBackground(new Color(75,75,75));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setPreferredSize(new Dimension(32,37));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();
        srch_tf = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        pAge_tf = new javax.swing.JTextField();
        addrress_tf = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        pnamet_tf = new javax.swing.JTextField();
        phone_num = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        pcashed_tf = new javax.swing.JTextField();
        temp_tf = new javax.swing.JTextField();
        pjob_tf = new javax.swing.JTextField();
        remain_tf = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        pAge = new javax.swing.JTextField();
        addrress = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        pcashed = new javax.swing.JTextField();
        search_tf1 = new javax.swing.JTextField();
        pjob = new javax.swing.JTextField();
        remain = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        temp = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        search_tf = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 189, 227));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 50));

        jPanel3.setBackground(new java.awt.Color(75, 75, 75));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(75, 75, 75));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Upadte Patient");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/updatepatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(75, 75, 75));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Delete Patient");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/deletepatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(75, 75, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Add New Patient");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/addpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(75, 75, 75));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Search");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/searchpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(75, 75, 75));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("View all Patients");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/viewpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(75, 75, 75));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Set Appointment");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setappoinment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );

        jPanel13.setBackground(new java.awt.Color(75, 75, 75));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Appointments");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/appointment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addGap(85, 85, 85))
        );

        jPanel14.setBackground(new java.awt.Color(75, 75, 75));
        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("LogOut");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 760));

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_name", "Pateint_age", "Address", "Phone_Number", "Patient's job", "Temperature", "Money_paid ", "Remaining money"
            }
        ));
        jTable1.setGridColor(java.awt.Color.white);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(33);
        jTable1.setSelectionBackground(new java.awt.Color(28, 199, 255));
        jTable1.setShowHorizontalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1020, 620));

        jTextField10.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jTextField10.setForeground(java.awt.Color.darkGray);
        jTextField10.setText("Username");
        jTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 352, 428, 55));

        srch_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        srch_tf.setForeground(java.awt.Color.darkGray);
        srch_tf.setText(" Search patient .......");
        srch_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        srch_tf.setCaretColor(java.awt.Color.gray);
        srch_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srch_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                srch_tfFocusLost(evt);
            }
        });
        srch_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_tfActionPerformed(evt);
            }
        });
        jPanel6.add(srch_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 304, 40));

        jButton6.setBackground(new java.awt.Color(0, 148, 50));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View All Patients");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 150, 40));

        jButton7.setBackground(new java.awt.Color(0, 148, 50));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 100, 40));

        jButton8.setBackground(new java.awt.Color(255, 0, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Download Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 160, 40));

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(java.awt.Color.white);
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 100, 40));

        jPanel4.add(jPanel6, "card3");

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pAge_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pAge_tf.setForeground(java.awt.Color.darkGray);
        pAge_tf.setText("Age");
        pAge_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pAge_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAge_tfActionPerformed(evt);
            }
        });
        jPanel5.add(pAge_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 217, 304, 53));

        addrress_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addrress_tf.setForeground(java.awt.Color.darkGray);
        addrress_tf.setText("Address");
        addrress_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        addrress_tf.setCaretColor(java.awt.Color.gray);
        addrress_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addrress_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addrress_tfFocusLost(evt);
            }
        });
        addrress_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrress_tfActionPerformed(evt);
            }
        });
        jPanel5.add(addrress_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 310, 302, 53));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.setForeground(java.awt.Color.darkGray);
        jTextField3.setText("Do you have any diseases ?");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        jTextField3.setCaretColor(java.awt.Color.gray);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 514, 221, 53));

        pnamet_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnamet_tf.setForeground(java.awt.Color.darkGray);
        pnamet_tf.setText("Patient name ");
        pnamet_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pnamet_tf.setCaretColor(java.awt.Color.gray);
        pnamet_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnamet_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnamet_tfFocusLost(evt);
            }
        });
        pnamet_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnamet_tfActionPerformed(evt);
            }
        });
        jPanel5.add(pnamet_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 110, 304, 53));

        phone_num.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        phone_num.setForeground(java.awt.Color.darkGray);
        phone_num.setText("Phone_Number");
        phone_num.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        phone_num.setCaretColor(java.awt.Color.gray);
        phone_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone_numFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone_numFocusLost(evt);
            }
        });
        phone_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numActionPerformed(evt);
            }
        });
        jPanel5.add(phone_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 417, 302, 53));

        jScrollPane1.setViewportView(jList1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 585, 312, -1));

        jButton2.setBackground(new java.awt.Color(0, 148, 50));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Add");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 514, 85, 53));

        pcashed_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pcashed_tf.setForeground(java.awt.Color.darkGray);
        pcashed_tf.setText("money_cashed");
        pcashed_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pcashed_tf.setCaretColor(java.awt.Color.gray);
        pcashed_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pcashed_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcashed_tfFocusLost(evt);
            }
        });
        pcashed_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcashed_tfActionPerformed(evt);
            }
        });
        jPanel5.add(pcashed_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 217, 331, 53));

        temp_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        temp_tf.setForeground(java.awt.Color.darkGray);
        temp_tf.setText("Temperature");
        temp_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        temp_tf.setCaretColor(java.awt.Color.gray);
        temp_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temp_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temp_tfFocusLost(evt);
            }
        });
        temp_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp_tfActionPerformed(evt);
            }
        });
        jPanel5.add(temp_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 110, 331, 53));

        pjob_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pjob_tf.setForeground(java.awt.Color.darkGray);
        pjob_tf.setText("Patient's job");
        pjob_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pjob_tf.setCaretColor(java.awt.Color.gray);
        pjob_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pjob_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pjob_tfFocusLost(evt);
            }
        });
        pjob_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjob_tfActionPerformed(evt);
            }
        });
        jPanel5.add(pjob_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 417, 331, 53));

        remain_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        remain_tf.setForeground(java.awt.Color.darkGray);
        remain_tf.setText("money_remaining");
        remain_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        remain_tf.setCaretColor(java.awt.Color.gray);
        remain_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remain_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remain_tfFocusLost(evt);
            }
        });
        remain_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remain_tfActionPerformed(evt);
            }
        });
        jPanel5.add(remain_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 318, 331, 53));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 654, 109, 50));

        jButton4.setBackground(new java.awt.Color(0, 148, 50));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Add Patient");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 654, 109, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/addpatient.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Add New Patient");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jPanel4.add(jPanel5, "card2");

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pAge.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pAge.setForeground(java.awt.Color.darkGray);
        pAge.setText("Age");
        pAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgeActionPerformed(evt);
            }
        });
        jPanel11.add(pAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 304, 53));

        addrress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addrress.setForeground(java.awt.Color.darkGray);
        addrress.setText("Address");
        addrress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        addrress.setCaretColor(java.awt.Color.gray);
        addrress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addrressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addrressFocusLost(evt);
            }
        });
        addrress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrressActionPerformed(evt);
            }
        });
        jPanel11.add(addrress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 302, 53));

        pname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pname.setForeground(java.awt.Color.darkGray);
        pname.setText("Patient name ");
        pname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pname.setCaretColor(java.awt.Color.gray);
        pname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnameFocusLost(evt);
            }
        });
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel11.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 304, 53));

        phone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        phone.setForeground(java.awt.Color.darkGray);
        phone.setText("Phone_Number");
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        phone.setCaretColor(java.awt.Color.gray);
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel11.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 302, 53));

        pcashed.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pcashed.setForeground(java.awt.Color.darkGray);
        pcashed.setText("money_cashed");
        pcashed.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pcashed.setCaretColor(java.awt.Color.gray);
        pcashed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pcashedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcashedFocusLost(evt);
            }
        });
        pcashed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcashedActionPerformed(evt);
            }
        });
        jPanel11.add(pcashed, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 331, 53));

        search_tf1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search_tf1.setForeground(java.awt.Color.darkGray);
        search_tf1.setText("Search to update .....");
        search_tf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        search_tf1.setCaretColor(java.awt.Color.gray);
        search_tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_tf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_tf1FocusLost(evt);
            }
        });
        search_tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tf1ActionPerformed(evt);
            }
        });
        jPanel11.add(search_tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 331, 50));

        pjob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pjob.setForeground(java.awt.Color.darkGray);
        pjob.setText("Patient's job");
        pjob.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        pjob.setCaretColor(java.awt.Color.gray);
        pjob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pjobFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pjobFocusLost(evt);
            }
        });
        pjob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjobActionPerformed(evt);
            }
        });
        jPanel11.add(pjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 331, 53));

        remain.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        remain.setForeground(java.awt.Color.darkGray);
        remain.setText("money_remaining");
        remain.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        remain.setCaretColor(java.awt.Color.gray);
        remain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remainFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remainFocusLost(evt);
            }
        });
        remain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainActionPerformed(evt);
            }
        });
        jPanel11.add(remain, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 331, 53));

        jButton10.setBackground(new java.awt.Color(0, 148, 50));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton10.setForeground(java.awt.Color.white);
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 109, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/updatepatient.png"))); // NOI18N
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Update Patient");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        temp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        temp.setForeground(java.awt.Color.darkGray);
        temp.setText("Temperature");
        temp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        temp.setCaretColor(java.awt.Color.gray);
        temp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempFocusLost(evt);
            }
        });
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });
        jPanel11.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 331, 53));

        jButton11.setBackground(new java.awt.Color(0, 148, 50));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton11.setForeground(java.awt.Color.white);
        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 130, 50));

        jPanel4.add(jPanel11, "card2");

        search_tf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search_tf.setForeground(java.awt.Color.darkGray);
        search_tf.setText(" Search patient .......");
        search_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        search_tf.setCaretColor(java.awt.Color.gray);
        search_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_tfFocusLost(evt);
            }
        });
        search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tfActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(0, 148, 50));
        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Search");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(637, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel15, "card5");

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 1060, 760));

        jButton1.setBackground(new java.awt.Color(10, 189, 227));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 60, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.red);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(10,189,227));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        
           this.setLocation(this.getX() +evt.getX() - xmouse, this.getY() + evt.getY() - ymouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        jPanel7.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
          jPanel8.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
          jPanel8.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
         jPanel9.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
         jPanel10.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        // TODO add your handling code here:
         jPanel12.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        // TODO add your handling code here:
         jPanel12.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel12MouseExited

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
         jPanel13.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
          jPanel13.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel13MouseExited

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        // TODO add your handling code here:
         jPanel14.setBackground(Color.RED);
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        // TODO add your handling code here:
        jPanel14.setBackground(new Color(75,75,75));
    }//GEN-LAST:event_jPanel14MouseExited

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
         dispose();
         JOptionPane.showMessageDialog(new LoginForm(),"تم تسجيل الخروج بنجاح ");
         new LoginForm().setVisible(true);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void pAge_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAge_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAge_tfActionPerformed

    private void addrress_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrress_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrress_tfActionPerformed

    private void addrress_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrress_tfFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_addrress_tfFocusGained

    private void addrress_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrress_tfFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addrress_tfFocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void pnamet_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnamet_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pnamet_tfFocusGained

    private void pnamet_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnamet_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pnamet_tfFocusLost

    private void pnamet_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnamet_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnamet_tfActionPerformed

    private void phone_numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_numFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numFocusGained

    private void phone_numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_numFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numFocusLost

    private void phone_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        final DefaultListModel model = new DefaultListModel();
        jList1.setModel(model);
        for(int j = 0; j<value.length; j++)
        {
           if(value[i].equals(""))
           {
             continue;
           }else{
              model.add(i,value[i]);
              
           }
        
        }
        String val = jTextField3.getText();  //.equals("Do you have any diseases ?") ? jTextField3.getText() : "";
        model.addElement(val);
        
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pcashed_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcashed_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashed_tfFocusGained

    private void pcashed_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcashed_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashed_tfFocusLost

    private void pcashed_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcashed_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashed_tfActionPerformed

    private void temp_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temp_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_temp_tfFocusGained

    private void temp_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temp_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_temp_tfFocusLost

    private void temp_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp_tfActionPerformed

    private void pjob_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pjob_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pjob_tfFocusGained

    private void pjob_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pjob_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pjob_tfFocusLost

    private void pjob_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjob_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjob_tfActionPerformed

    private void remain_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remain_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_remain_tfFocusGained

    private void remain_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remain_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_remain_tfFocusLost

    private void remain_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remain_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remain_tfActionPerformed

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusGained
        // TODO add your handling code here:
        if (addrress_tf.getText().equals("Username")) {
            addrress_tf.setText("");
            addrress_tf.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField10FocusGained

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:

        if (addrress_tf.getText().isEmpty()) {
            addrress_tf.setForeground(Color.GRAY);
            addrress_tf.setText("Username");
        }
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void srch_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srch_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_tfFocusGained

    private void srch_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srch_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_tfFocusLost

    private void srch_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_tfActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
               
        // delete all records in jtable 
        
        jTable1.removeAll();
        tableModel.setNumRows(0);
        
       // view all patients from database into table
        try{
            
         Connection con = DBConnection.get_DefaultConnection();
         Statement st;
         st = con.createStatement(); 
         
         // select all patients into table
         String select_sql = "SELECT * FROM `patient_table`";
         
         ResultSet rs = st.executeQuery(select_sql);
         
         while (rs.next()) {
                        
           String name = rs.getString("name");
           String age = rs.getInt("age")+"";
           String address = rs.getString("address");
           String phone_number = rs.getString("phone_number");
           String temp = rs.getInt("temp")+"";
           String patient_job = rs.getString("patient_job");
           String money_paid = rs.getFloat("money_paid")+"";
           String money_remaining = rs.getFloat("money_remaining")+"";
           
           String[] data = { name, age , address , phone_number , 
               temp, patient_job, money_paid, money_remaining
           } ;
           
           tableModel.addRow(data);
           
         }
         
         jTable1.setModel(tableModel);
         
        }catch(SQLException Ex)
        {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, Ex);
        
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                   
         try{
            
         Connection con = DBConnection.get_DefaultConnection();
         Statement st;
         st = con.createStatement(); 
         
         // select all patients into table
         String select_sql = "SELECT `name`, `age`, `address`, `phone_number`, "
                + "`temp`, `patient_job`, `money_paid`, `money_remaining` FROM `patient_table` WHERE name = '"+srch_tf.getText()+"'";
         
          ResultSet rs = st.executeQuery(select_sql);
         
               
          if(rs.next()){
                      
           String name = rs.getString("name");
           String age = rs.getInt("age")+"";
           String address = rs.getString("address");
           String phone_number = rs.getString("phone_number");
           String temp1= rs.getInt("temp")+"";
           String patient_job = rs.getString("patient_job");
           String money_paid = rs.getFloat("money_paid")+"";
           String money_remaining = rs.getFloat("money_remaining")+"";
           
           
           jTable1.removeAll();
           tableModel.setNumRows(0);
           
           
            String[] data = { name, age , address , phone_number , 
               temp1, patient_job, money_paid, money_remaining} ;
           
           tableModel.addRow(data);
           jTable1.setModel(tableModel);

          }
          
         
        }catch(SQLException ex )
        {
           
          Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        // TODO add your handling code here:        
        String pname = pnamet_tf.getText();
        String pAge = pAge_tf.getText();
        String paddress = addrress_tf.getText();
        String phone_number = phone_num.getText();
        String ptemp = temp_tf.getText();
        String pcashed = pcashed_tf.getText();
        String remain_money = remain_tf.getText();
        String pjob = pjob_tf.getText();
        
        // check if all textfields are not empty !
        if(pname!= "" || pAge != "" || paddress!= "" ||  phone_number!= "" ||  ptemp!= "" ||  pcashed!= "" 
                || remain_money!= "" || pjob!= "")
         {
             // setup connecion to db server                        
             try 
             {
                   Connection con = DBConnection.get_DefaultConnection();
                   Statement st;
                   st = con.createStatement();                   
                    // insert data  from all textfields into my sql db
                   String insert_sql = "INSERT INTO `patient_table`"
                    + "(`name`, `age`, `address`, `phone_number`, `temp`, `patient_job`, `money_paid`, `money_remaining`) "
                    + "VALUES (?, ?, ?, ?, ? ,? ,? ,?)";
                    /*       
                    + "('"+pname+"','"+(Integer.parseInt(pAge))+"','"+paddress+"','"
                    + ""+phone_number+"','"+(Integer.parseInt(ptemp))+"','"
                    +Float.parseFloat(pcashed)+"','"+Float.parseFloat(remain_money)+"','"+pjob+"')";
                    */
                    // prepared statement it is a way that is more effiecient and flexible to execute secure sql query
                      PreparedStatement preparedStmt = con.prepareStatement(insert_sql);
                      preparedStmt.setString (1,pname);
                      preparedStmt.setInt    (2, (Integer.parseInt(pAge)));
                      preparedStmt.setString (3, paddress);
                      preparedStmt.setString (4, phone_number);
                      preparedStmt.setInt    (5, (Integer.parseInt(ptemp)));
                      preparedStmt.setString (6, pjob);
                      preparedStmt.setFloat  (7, Float.parseFloat(pcashed));
                      preparedStmt.setFloat (8, Float.parseFloat(remain_money));

                      // execute the preparedstatement
                      preparedStmt.execute();
                      JOptionPane.showMessageDialog(this,"تم الاضافة بنجاح   : )");
                      
             
              }catch(SQLException ex){
                
                  Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);        
             }
             
         } else
         {
             
             JOptionPane.showMessageDialog(this,"من فضلك اكمل الحقول الفارغة  !");              
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        // TODO add your handling code here:     
        pnamet_tf.setText("");
        pAge_tf.setText("");
        addrress_tf.setText("");
        phone_num.setText("");
        temp_tf.setText("");
        pcashed_tf.setText(""); 
        remain_tf.setText("");
        pjob_tf.setText("");
             
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
        if(evt.getSource()==jPanel2)
        {
           jPanel5.setVisible(true);
           jPanel6.setVisible(false);
           jPanel11.setVisible(false);
        
        }
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:        
        if(evt.getSource()==jPanel10)
        {
           
           jPanel6.setVisible(true);
           jButton6.setVisible(true);
           //jButton6.invalidate();
           jButton8.setVisible(true);
           //jButton8.invalidate();
           jPanel5.setVisible(false);         
           jPanel11.setVisible(false);
        
        }
        
    }//GEN-LAST:event_jPanel10MouseClicked

    private void pAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAgeActionPerformed

    private void addrressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addrressFocusGained

    private void addrressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_addrressFocusLost

    private void addrressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrressActionPerformed

    private void pnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameFocusGained

    private void pnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameFocusLost

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFocusLost

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void pcashedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcashedFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashedFocusGained

    private void pcashedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcashedFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashedFocusLost

    private void pcashedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcashedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcashedActionPerformed

    private void search_tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tf1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tf1FocusGained

    private void search_tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tf1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tf1FocusLost

    private void search_tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tf1ActionPerformed

    private void pjobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pjobFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pjobFocusGained

    private void pjobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pjobFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pjobFocusLost

    private void pjobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjobActionPerformed

    private void remainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remainFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_remainFocusGained

    private void remainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remainFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_remainFocusLost

    private void remainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        // search patient from db and rerurn data into textFields 
        try{
            
         Connection con = DBConnection.get_DefaultConnection();
         Statement st;
         st = con.createStatement(); 
         
         // select all patients into table
         String select_sql = "SELECT `name`, `age`, `address`, `phone_number`, "
                + "`temp`, `patient_job`, `money_paid`, `money_remaining` FROM `patient_table` WHERE name = '"+search_tf1.getText()+"'";
         
          ResultSet rs = st.executeQuery(select_sql);
         
               
          if(rs.next()){
        
           String name = rs.getString("name");
           String age = rs.getInt("age")+"";
           String address = rs.getString("address");
           String phone_number = rs.getString("phone_number");
           String temp1= rs.getInt("temp")+"";
           String patient_job = rs.getString("patient_job");
           String money_paid = rs.getFloat("money_paid")+"";
           String money_remaining = rs.getFloat("money_remaining")+"";
           
           pname.setText(name);
           pAge.setText(age);
           addrress.setText(address);
           phone.setText(phone_number);
           temp.setText(temp1);
           pcashed.setText(money_paid);
           remain.setText(money_remaining);
           pjob.setText(patient_job);
           
          }
          
         
        }catch(SQLException ex )
        {
           
          Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tempFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tempFocusGained

    private void tempFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tempFocusLost

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Update patient already exist
        
        String pname1 = pname.getText();
        String pAge1= pAge.getText();
        String paddress = addrress.getText();
        String phone_number = phone.getText();
        String ptemp = temp.getText();
        String pcashed1 = pcashed.getText();
        String remain_money = remain.getText();
        String pjob1 = pjob.getText();
        
      try{
            
         Connection con = DBConnection.get_DefaultConnection();
         Statement st;
         st = con.createStatement(); 
        
        String sql = "UPDATE `patient_table` SET `name`= '"+pname1+"',`age`='"+Integer.parseInt(pAge1)+"',"
                + "`address`='"+paddress+"',`phone_number`='"+phone_number+"',`temp`= '"+Integer.parseInt(ptemp)+"',`patient_job`='"+pjob1+"'"
                + ",`money_paid`='"+Float.parseFloat(pcashed1)+"',`money_remaining`='"+Float.parseFloat(remain_money)+"'"
        + " WHERE name = '"+search_tf1.getText()+"'";
        
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(this,"تم التعديل بنجاح   : )");
        
         }catch(SQLException ex)
         {
               Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
         
         }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        
        if(evt.getSource()==jPanel7)
        {          
           jPanel6.setVisible(false);
           jPanel5.setVisible(false);         
           jPanel11.setVisible(true);
        
        }
        
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==jPanel9)
        {
           
           jPanel6.setVisible(true);
           jButton6.setVisible(false);
           jButton6.invalidate();
           jButton7.setVisible(true);
           jButton8.setVisible(false);
           jButton8.invalidate();
           jButton9.setVisible(false);
           jButton9.invalidate();
           jPanel5.setVisible(false);             
           jPanel11.setVisible(false);
        
        }
        
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
      
        if(evt.getSource()==jPanel8)
        {
           
           jPanel6.setVisible(true);
           jButton6.setVisible(false);
           jButton6.invalidate();
           jButton8.setVisible(false);
           jButton8.invalidate();
           jButton9.setVisible(true);
          // jButton9.invalidate();
          jButton7.setVisible(true);
          // jButton7.invalidate();
           jPanel5.setVisible(false);             
           jPanel11.setVisible(false);
        
        }
        
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void search_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusGained

    private void search_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusLost

    private void search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         String search_tf = srch_tf.getText();
         
        try{
        
              Connection con = DBConnection.get_DefaultConnection();
              Statement st;
              st = con.createStatement();  
              String sql = "DELETE FROM `patient_table` WHERE name ='"+search_tf+"'";
              st.execute(sql);
              JOptionPane.showMessageDialog(this,"Record is deleted from the table successfully.................."); 
              
        }catch(SQLException ex)
        {
           Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrress;
    private javax.swing.JTextField addrress_tf;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField pAge;
    private javax.swing.JTextField pAge_tf;
    private javax.swing.JTextField pcashed;
    private javax.swing.JTextField pcashed_tf;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phone_num;
    private javax.swing.JTextField pjob;
    private javax.swing.JTextField pjob_tf;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pnamet_tf;
    private javax.swing.JTextField remain;
    private javax.swing.JTextField remain_tf;
    private javax.swing.JTextField search_tf;
    private javax.swing.JTextField search_tf1;
    private javax.swing.JTextField srch_tf;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField temp_tf;
    // End of variables declaration//GEN-END:variables
}
